### ISSUE TITLE
Verlinkung eures Beitrags im Haupt-Repository

### ISSUE THREAD

**Issue by jonico** [CreeperShift/Pandemie#5]
Hallo @CreeperShift,

bis jetzt haben wir eure tolle Einsendung noch nicht in https://github.com/informatiCup/informatiCup2020/tree/master/github-sonderpreis gesehen, wollt ihr einen pull-request stellen?

Liebe Grüße und frohe Ostern

@jonico

:octocat: ❤️

**Comment by CreeperShift** [comment]
Urgh, eigentlich wollte ich dieses Projekt nicht oeffentlich zur schau stellen, da meine beiden Mitstreiter die mich dazu ueberredet haben, hier mit zu machen, ihren Arsch nicht hoch bekommen haben und 0 Arbeit rein gesteckt haben, mindestens 60 Stunden Arbeit von mit zu nichte gemacht haben, aber ich denke es sollte auch nicht verloren gehen. Werde einen pull request machen, danke!
